In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.python import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, Conv2D, Dropout, MaxPooling2D
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly import tools
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [18]:
IMG_ROWS = 28
IMG_COLS = 28
NUM_CLASSES = 10
TEST_SIZE = 0.2
RANDOM_STATE = 2018
#Model
NO_EPOCHS = 100
BATCH_SIZE = 128

In [19]:
dataset_test = pd.read_csv('/content/drive/MyDrive/Datasets/dataset_test.csv')
dataset_train = pd.read_csv( '/content/drive/MyDrive/Datasets/dataset_train_final.csv')

In [20]:
y_train = dataset_train["label"]
y_train = y_train.to_numpy()
y_train = y_train.astype(int)
y_train

array([2, 9, 6, ..., 3, 3, 3])

In [21]:
x_train = dataset_train.drop('label', axis=1)
x_train = x_train.to_numpy()
x_train = np.array(x_train,dtype=np.uint8)
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [22]:
y_train = dataset_train["label"]
y_train = y_train.to_numpy()
y_train = y_train.astype(int)
y_train

array([2, 9, 6, ..., 3, 3, 3])

In [23]:
y_test = dataset_test["label"]
y_test = y_test.to_numpy()
y_test = np.array(y_test,dtype=np.uint8)
y_test = y_test.astype(int)

In [24]:
x_test = dataset_test.drop('label',1)
x_test = x_test.to_numpy()
x_test = np.array(x_test, dtype= np.uint8)
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [25]:
class_names = ['T-shirt','Trouser',' Pullover','Dress', 'Coat'
, 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle Boot','Lips','Eyewear'
,'Nails','Headewear', 'FlipLops', 'Ties']
class_names

['T-shirt',
 'Trouser',
 ' Pullover',
 'Dress',
 'Coat',
 'Sandal',
 'Shirt',
 'Sneaker',
 'Bag',
 'Ankle Boot',
 'Lips',
 'Eyewear',
 'Nails',
 'Headewear',
 'FlipLops',
 'Ties']

In [26]:
#model cần thêm 1 chiều cho image
from keras.utils.all_utils import to_categorical
x_train = x_train.reshape(len(x_train),28,28,1)
x_test = x_test.reshape(len(x_test),28,28,1)
#one hot cho output
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_test[1000]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [27]:
model = Sequential()
# Add convolution 2D
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 padding='same',
                 input_shape=(28,28, 1)))
model.add(MaxPooling2D((2, 2)))
# Add dropouts to the model
model.add(Dropout(0.25))
model.add(Conv2D(64, 
                 kernel_size=(3, 3), 
                 activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
# Add dropouts to the model
model.add(Dropout(0.25))
model.add(Conv2D(128, (3, 3), activation='relu'))
# Add dropouts to the model
model.add(Dropout(0.4))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
# Add dropouts to the model
model.add(Dropout(0.3))
model.add(Dense(16, activation='softmax'))


model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [28]:
train_model = model.fit(x_train, y_train,
                  batch_size=BATCH_SIZE,
                  epochs=NO_EPOCHS,
                  verbose=1,
                  validation_data=(x_test, y_test))

Epoch 1/100
993/993 [==============================] - 7s 6ms/step - loss: 0.9882 - accuracy: 0.7043 - val_loss: 1.1026 - val_accuracy: 0.7032
Epoch 2/100
993/993 [==============================] - 6s 6ms/step - loss: 0.4896 - accuracy: 0.8257 - val_loss: 1.2378 - val_accuracy: 0.7220
Epoch 3/100
993/993 [==============================] - 6s 6ms/step - loss: 0.4136 - accuracy: 0.8541 - val_loss: 1.1576 - val_accuracy: 0.7439
Epoch 4/100
993/993 [==============================] - 6s 6ms/step - loss: 0.3758 - accuracy: 0.8662 - val_loss: 0.9885 - val_accuracy: 0.7490
Epoch 5/100
993/993 [==============================] - 6s 6ms/step - loss: 0.3549 - accuracy: 0.8745 - val_loss: 1.1567 - val_accuracy: 0.7535
Epoch 6/100
993/993 [==============================] - 6s 6ms/step - loss: 0.3377 - accuracy: 0.8792 - val_loss: 1.3987 - val_accuracy: 0.7470
Epoch 7/100
993/993 [==============================] - 6s 6ms/step - loss: 0.3264 - accuracy: 0.8840 - val_loss: 1.2825 - val_accuracy: 0.7443

In [29]:
model.save('fashion.h5')

In [31]:
def create_trace(x,y,ylabel,color):
        trace = go.Scatter(
            x = x,y = y,
            name=ylabel,
            marker=dict(color=color),
            mode = "markers+lines",
            text=x
        )
        return trace

In [33]:
def plot_accuracy_and_loss(train_model):
    hist = train_model.history
    acc = hist['accuracy']
    val_acc = hist['val_accuracy']
    loss = hist['loss']
    val_loss = hist['val_loss']
    epochs = list(range(1,len(acc)+1))
    
    trace_ta = create_trace(epochs,acc,"Training accuracy", "Green")
    trace_va = create_trace(epochs,val_acc,"Validation accuracy", "Red")
    trace_tl = create_trace(epochs,loss,"Training loss", "Blue")
    trace_vl = create_trace(epochs,val_loss,"Validation loss", "Magenta")
   
    fig = tools.make_subplots(rows=1,cols=2, subplot_titles=('Training and validation accuracy',
                                                             'Training and validation loss'))
    fig.append_trace(trace_ta,1,1)
    fig.append_trace(trace_va,1,1)
    fig.append_trace(trace_tl,1,2)
    fig.append_trace(trace_vl,1,2)
    fig['layout']['xaxis'].update(title = 'Epoch')
    fig['layout']['xaxis2'].update(title = 'Epoch')
    fig['layout']['yaxis'].update(title = 'Accuracy', range=[0,1])
    fig['layout']['yaxis2'].update(title = 'Loss', range=[0,1])

    
    iplot(fig, filename='accuracy-loss')

plot_accuracy_and_loss(train_model)

/usr/local/lib/python3.7/dist-packages/plotly/tools.py:465: DeprecationWarning:

plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead

